// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC8dttQUvMXmifDEwlQf013QDCr1W_1wQ',
    appId: '1:738330987623:web:55ea4f3f4a5e7ac35018c2',
    messagingSenderId: '738330987623',
    projectId: 'wanderhub-3410',
    authDomain: 'wanderhub-3410.firebaseapp.com',
    storageBucket: 'wanderhub-3410.appspot.com',
    measurementId: 'G-VM7TL4Z8NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0hTOsb3tqM8FBt0TD3fJRA9yABDTh4PU',
    appId: '1:738330987623:android:a02fffeb52e9a3175018c2',
    messagingSenderId: '738330987623',
    projectId: 'wanderhub-3410',
    storageBucket: 'wanderhub-3410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxzXsIykMfYXtaU6B70Q_pzCd7Nk9cQ4A',
    appId: '1:738330987623:ios:ced88306ebfc164d5018c2',
    messagingSenderId: '738330987623',
    projectId: 'wanderhub-3410',
    storageBucket: 'wanderhub-3410.appspot.com',
    iosBundleId: 'com.example.wanderhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxzXsIykMfYXtaU6B70Q_pzCd7Nk9cQ4A',
    appId: '1:738330987623:ios:8f2b874db2c079b65018c2',
    messagingSenderId: '738330987623',
    projectId: 'wanderhub-3410',
    storageBucket: 'wanderhub-3410.appspot.com',
    iosBundleId: 'com.example.wanderhub.RunnerTests',
  );
}
